import Head from "next/head";
import { Inter } from "next/font/google";
import { connectDb } from "../utils/db";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  connectDb();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline text-red-300">Iahn</h1>

      <button>Hi</button>
    </>
  );
}
